server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ccpms?zeroDateTimeBehavior=convertToNull
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springbootccpms

file:
  ip: localhost